Models/Wedding.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace WeddingPlanner.Models
{

public class Wedding
    {
        [Key]
        public int WeddingId {get;set;}
        [Required]
        public string WedderOne {get;set;}
        [Required]
        public string WedderTwo {get;set;}
        [Required]
        public string Address {get;set;}
        [Required]
        [FutureDate]
        public DateTime WeddingDate {get;set;} 

        //foreign key
        public int UserId {get;set;}
        //-------------------------------------------------
        //navagational property 
        public User Planner {get;set;}
        public List<Reservation> GuestList {get;set;}
        //-------------------------------------------------
        public DateTime CreatedAt {get;set;} = DateTime.Now;
        public DateTime UpdatedAt {get;set;} = DateTime.Now;
    }
    // Custom Validation
    public class FutureDateAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            DateTime date;
            if(value is DateTime)
            {
                date = (DateTime)value;
            }
            else
            {
                return new ValidationResult("Invalid datetime!");
            }
            if(date < DateTime.Now)
            {
                return new ValidationResult("Date must be in the future");
            }
            return ValidationResult.Success;
        }

    }

}

Controllers/ResponseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using WeddingPlanner.Models;

namespace WeddingPlanner.Controllers
{
    public class ResponseController : Controller
    {
        private HomeContext dbContext;
        public ResponseController(HomeContext context)
        {
            dbContext = context;
        }

        [HttpGet("/rsvp/{WeddingId}/{Status}")]
        public IActionResult RSVP(int WeddingId, String Status)
        {
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction ("LogOut", "Home");
            }
            else
            {
                if(Status == "add")
                {
                    Reservation NewRsvp = new Reservation();
                    NewRsvp.UserId = (int)HttpContext.Session.GetInt32("UserId");
                    NewRsvp.WeddingId = WeddingId;
                    dbContext.Rsvps.Add(NewRsvp);
                    dbContext.SaveChanges();
                    return RedirectToAction("Dashboard", "Wedding");
                }
                if(Status == "remove")
                {
                    Reservation remove = dbContext.Rsvps.FirstOrDefault(r => r.WeddingId == WeddingId && r.UserId == HttpContext.Session.GetInt32("UserId"));

                    dbContext.Rsvps.Remove(remove);
                    dbContext.SaveChanges();
                    return RedirectToAction("Dashboard", "Wedding");

                }
                return View("Dashboard");
            }
        }

    }
}

Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using WeddingPlanner.Models;

namespace WeddingPlanner.Controllers
{
    [Route("Wedding")]
    public class WeddingController : Controller
    {
        private HomeContext dbContext;
        //Change this controller to new name
        public WeddingController(HomeContext context)
        {
            dbContext = context;
        }

        [HttpGet("")]
        public IActionResult DashBoard()
        {
            if(HttpContext.Session.GetInt32("UserId") == null )
            {
                return RedirectToAction ("LogOut","Home");
            }
            else 
            {
                //This code Compares Dates and does not display past dates
                List<Wedding> AllWeddings = dbContext.Weddings.Include(w => w.GuestList)
                .ThenInclude(r => r.Guest).Where(c => c.WeddingDate > DateTime.Now).ToList();
                
                ViewBag.User = dbContext.Users.Include(u => u.CreatedWeddings).Include(u => u.Weddings).ThenInclude( r => r.Attending).FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));

                return View ("Dashboard",AllWeddings);
                
            }
        }
            [HttpGet("new")]
            public IActionResult NewWedding()
            {
                ViewBag.User = dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));
                return View();
            }

            [HttpPost("create")]
            public IActionResult CreateWedding(Wedding newWedding)
            {
                Console.WriteLine("Print 1");
                if(HttpContext.Session.GetInt32("UserId") == null)
                {
                    return RedirectToAction ("LogOut", "Home");
                }
                else
                {
                    if(ModelState.IsValid)
                    {
                        Console.WriteLine("Print 2");
                        dbContext.Weddings.Add(newWedding);
                        dbContext.SaveChanges();
                        return Redirect($"/wedding/show/{newWedding.WeddingId}");
                    }
                    else
                    {
                        Console.WriteLine("Print 3");
                        ViewBag.User = dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));
                        return View("NewWedding");
                    }
                }
            }

            [HttpGet("/wedding/show/{WeddingId}")]
            public IActionResult ShowWedding(int WeddingId)
            {
                if(HttpContext.Session.GetInt32("UserId") == null)
                {
                    return RedirectToAction ("LogOut", "Home");
                }
                else
                {
                    Wedding myWedding = dbContext.Weddings.Include(w => w.GuestList).ThenInclude( r => r.Guest).FirstOrDefault(w => w.WeddingId == WeddingId);

                    ViewBag.User = dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));
                    return View("ShowWedding", myWedding);
                }
            }

            [HttpGet("/destroy/{WeddingId}")]
            public IActionResult Destroy(int WeddingId)
            {
                if(HttpContext.Session.GetInt32("UserId") == null)
                {
                    return RedirectToAction ("LogOut", "Home");
                }
                else
                {
                    Wedding RemoveWedding = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == WeddingId);
                    if(RemoveWedding == null)
                    {
                        return RedirectToAction("Dashboard");

                    }
                    dbContext.Weddings.Remove(RemoveWedding);
                    dbContext.SaveChanges();
                    return RedirectToAction("Dashboard");
                }
            }
        
    }
}

Views/Wedding/Dashboard.cshtml
@model List<Wedding>

<h1>Welcome To The Wedding Planner!</h1>
<a asp-action="LogOut" asp-controller="Home">Logout</a>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Wedding</th>
            <th>Date</th>
            <th># of Guest</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var w in Model)
        {
            <tr>
                <td><a asp-action="ShowWedding" asp-controller="Wedding" asp-route-WeddingId="@w.WeddingId">@w.WedderOne & @w.WedderTwo </a></td>
                <td>@w.WeddingDate.ToString("d")</td>
                <td>@w.GuestList.Count</td>
                @if(@ViewBag.User.UserId == @w.UserId)
                {
                    <td><a asp-action="Destroy" asp-controller="Wedding" asp-route-WeddingId = "@w.WeddingId">Delete</a></td>
                }
                else
                {
                    @if(w.GuestList.Any(r => r.UserId != ViewBag.User.UserId) || w.GuestList.Count == 0)
                    {
                        <td><a asp-action="RSVP" asp-controller="Response" asp-route-WeddingId = "@w.WeddingId" asp-route-Status = "add" >RSVP</a></td>
                    }
                    @if(w.GuestList.Any(r => r.UserId == ViewBag.User.UserId))
                    {
                        <td><a asp-action="RSVP" asp-controller="Response" asp-route-WeddingId = "@w.WeddingId" asp-route-Status = "remove" >Un-RSVP</a></td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

<a asp-action="NewWedding" asp-controller="Wedding">Add a wedding </a>

Views/Wedding/NewWedding.cshtml
@model Wedding
<header>
<h1> @ViewBag.User.FirstName, Plan your wedding</h1>
<a asp-action = "Dashboard" asp-controller = "Wedding"></a>
<a asp-action = "LogOut" asp-controller = "Home"></a>
</header>

<div>
    <span asp-validation-for="WedderOne"></span>
    <span asp-validation-for="WedderTwo"></span>
    <span asp-validation-for="WeddingDate"></span>
    <span asp-validation-for="Address"></span>
</div>

<form asp-action="CreateWedding" asp-controller="Wedding" method="post">
    <input type="hidden" asp-for="UserId" value="@ViewBag.User.UserId">
    <label asp-for="WedderOne"></label>
    <input asp-for="WedderOne"><br>
    <label asp-for="WedderTwo"></label>
    <input asp-for="WedderTwo"><br>
    <label asp-for="WeddingDate"></label>
    <input type="Date" asp-for="WeddingDate"><br>
    <label asp-for="Address"></label>
    <input asp-for="Address"><br>
    <input type="submit" value="Create">
    </form>

Views/Wedding/ShowWedding.cshtml
@model Wedding
<header>
<h1>@Model.WedderOne & @Model.WedderTwo's Wedding </h1>
<a asp-action="Dashboard" asp-controller="Wedding">Dashboard</a>
<a asp-action="LogOut" asp-controller="Home">Logout</a>
</header>
<h4>When: @Model.WeddingDate.ToString("MM/dd/yyyy")</h4>
<h4>Where: @Model.Address</h4>
<div>
    <h6>Guest list:</h6>
    @if(@Model.GuestList.Count == 0 )
    {
        <p>No one loves us.</p>
    }
    @foreach( var r in @Model.GuestList)
    {
        <p>@r.Guest.FirstName @r.Guest.LastName </p>
    }
</div>